/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MyApp;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.Arrays;

class AppTest {

    @Test
    public void testSameNumberArray() {
        ArrayList<Integer> arr = new ArrayList<>(Arrays.asList(3, 3, 3, 3, 3, 3));
        int k = 2;
        int number = 1;
        assertTrue(App.searchInRemainderedArray(arr, k, number));
    }

    @Test
    public void testZero() {
        ArrayList<Integer> arr = new ArrayList<>(Arrays.asList(1, 45, 74, 20, 35, 64, 58, 13, 5, 92));     
        int k = 0;
        int number = 5;
        assertFalse(App.searchInRemainderedArray(arr, k, number));
    }

    @Test
    public void testNegativeNumber() {
        ArrayList<Integer> arr = new ArrayList<>(Arrays.asList(1, 45, 74, 20, 35, 64, 58, 13, 5, 92));     
        int k = 5;
        int number = -7;
        assertFalse(App.searchInRemainderedArray(arr, k, number));
    }

    @Test
    public void testEmptyArrayList() {
        ArrayList<Integer> arr = new ArrayList<>();     
        int k = 5;
        int number = 7;
        assertFalse(App.searchInRemainderedArray(arr, k, number));
    }
}
